### ISSUE TITLE
how can use magnizoom with Blob image source

### ISSUE THREAD

**Issue by hamidroozkhosh** [henczi/ng-magnizoom#10]
hi
is it possible to use Blob  as source ?
thank you very much.

**Comment by henczi** [comment]
Hi @hamidroozkhosh!

Yes, for sure.

You can use the `URL.createObjectURL` function to create an object URL of your Blob. Then you can pass this URL to the magnizoom component.

```ts
// example.component.ts
this.blob_img_url = URL.createObjectURL(blob_image)
```

```html
<!-- example.component.html -->
<ng-magnizoom *ngIf="blob_img_url" [imageSrc]="blob_img_url"></ng-magnizoom>
```
