### ISSUE TITLE
Can we customize the height and width of the lens?

### ISSUE THREAD

**Issue by singh-anit** [henczi/ng-magnizoom#11]
It will be amazing if we could modify the height, width as well as the position of the lens.

**Comment by henczi** [comment]
Currently, it is not possible.

The reason it is not implemented yet is the way how the width and the height of the lens are handled. The canvas size is equal to the full image size, and the lens size is relative to the canvas size (it is half of both side).

If it would be possible to set an explicit value in px for the lens size, then it would result different lens size for different sized images, which would be very weird - I think.

Despite this theoretical issue, it would not be too hard to implement this feature, so it might be in the next version.

**Comment by henczi** [comment]
This has been released in 1.1.0

**Comment by singh-anit** [comment]
Thank you for the latest release @henczi I used the resizing lens functionality and I must say it is well thought out. Even though I think we can still add functionality to set the position of the lens as some users might have the requirement of showing the lens outside the parent container, for example from another library is [here](https://stackblitz.com/edit/ng-img-magnifier?file=src%2Fapp%2Fapp.component.ts).
