### ISSUE TITLE
img src binding

### ISSUE THREAD

**Issue by eslam96** [henczi/ng-magnizoom#12]
tried to bind img src proberty to a dynamic value but it didn't work, trying to bind the images with a paginator

**Comment by henczi** [comment]
Yes, you are right, the dynamic `imageSrc` parameter was not handled by the package.

I released a new version that supports this, so it is included in version 1.2.0.
> It is not perfect, especially when the image is big or the network is slow (the old image is shown until the new one is fully loaded), or when `imageSrc` changes before the previous image are loaded.
