### ISSUE TITLE
NgMagnizoom is not compatible with Ivy

### ISSUE THREAD

**Issue by aminahasimbegovic** [henczi/ng-magnizoom#13]
Hi! 

When trying to import NgMagnizoomModule in my AppModule, I get an error: 

`'NgMagnizoomModule' does not appear to be an NgModule class.`

`magnizoom.module.d.ts(1, 22): This likely means that the library (ng-magnizoom) which declares NgMagnizoomModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

I'm using Angular 14.

Any plans on supporting Ivy?

**Comment by henczi** [comment]
Hi @aminahasimbegovic !

It should work with Ivy (I've already tried it with Angular 15)

Can you share the details?

Please make sure you import the module directly from 'ng-magnizoom' and not using any subfolder. (and try manually running "ngcc") 

```
import { NgMagnizoomModule } from 'ng-magnizoom';
```

**Comment by aminahasimbegovic** [comment]
> Hi @aminahasimbegovic !
> 
> It should work with Ivy (I've already tried it with Angular 15)
> 
> Can you share the details?
> 
> Please make sure you import the module directly from 'ng-magnizoom' and not using any subfolder. (and try manually running "ngcc")
> 
> ```
> import { NgMagnizoomModule } from 'ng-magnizoom';
> ```

Big thanks for a quick response and your help @henczi !

Running ngcc manually helped :) 🥳
