### ISSUE TITLE
NgMagnizoom is not compatible with Ivy. Angular 17 does not have ngcc to make it compatible.

### ISSUE THREAD

**Issue by tornelliotavio** [henczi/ng-magnizoom#15]
I encountered a problem when attempting to use this library in a project built with Angular 17. The issue arises because the library is not an Ivy module, and Angular 17 no longer includes ngcc for compatibility with non-Ivy modules.

As a workaround, I had to manually copy the module from an earlier Angular version project that contained the __ivy_ngcc__ folder. This allowed me to make it work with Angular 17. It would be beneficial if the library could be updated to support Ivy natively or if there could be some guidance on how to handle this compatibility issue more seamlessly.

**Comment by henczi** [comment]
Hi @tornelliotavio 

Version `1.4.0` should be compatible with Angular 17, could you give it a try?
